development:
  adapter: postgresql
  encoding: utf8
  database: gbApi_development
  pool: 5


test:
  adapter: postgresql
  encoding: utf8
  database: gbApi_test
  pool: 5


production:
  adapter: postgresql
  encoding: utf8
  database: gbApi_production
  pool: 5

